### ISSUE TITLE
version without cas and default control bindings

### ISSUE THREAD

**Issue by cwoomi** [fixerid/sb-projects#1]
if :nav<1 then :p0=4 :y0=4 :r0=4 g=0 f=0 goto1 end
xD=:aa-:xj yD=:bb-:yj zD=:cc-:zj Dt=sqrt((xD)^2+(yD)^2+(zD)^2)
if f<1 then x0=:xj y0=:yj z0=:zj Do=Dt f=1 r=0 p0=0 p1=0 p2=0 end
da=sqrt((:xj-x0)^2+(:yj-y0)^2+(:zj-z0)^2) d0=d1 d1=Dt v1=d0-d1
dx=(Do-da)*1.05+5000
if Dt>dx then :fwd=0 if abs(v1)<1 then f=0 g=0 goto1 end end
e=10^6 ds=e*sqrt((:xa-:xj)^2+(:ya-:yj)^2+(:za-:zj)^2)  
Dd=ds/Dt  xs=:xj+Dd*xD/e ys=:yj+Dd*yD/e zs=:zj+Dd*zD/e  
vr=xs-:xa vs=ys-:ya vt=zs-:za vj=:xk-:xj vk=:yk-:yj vl=:zk-:zj
va=:xa-:xj vb=:ya-:yj vc=:za-:zj vx=vk*vc-vb*vl vy=-(vj*vc-va*vl)
vz=vj*vb+va*vk pj=vr*vj+vs*vk+vt*vl px=vr*vx+vs*vy+vz*vt 
n="\n" :dd=(Do-da)+n+Dt+n+v1+"\npj:"+pj+" px:"+px+" r:"+r+" g:"+g
r=25//p0=p1 p1=p2 p2=px if p0!=0 then r=abs((p2-p0)/2) end
if Dt<5000 then :nav=0 :fwd=0 end if g>0 then goto1 end
if pj<0 then :FCURotationalPitch=8 end 
if pj>0 then :FCURotationalPitch=-8 end 
if px>0 then :FCURotationalYaw=8 end 
if px<0 then :FCURotationalYaw=-8 end
if pj>-r and pj<r and px>-r and px<r then g=1 :FCUForward=100 end goto1
//tips to Fixerid. Even 1 cred or kind words appreciated

**Comment by fixerid** [comment]
Made yolol_nav_only without cas integration. Also yolol_nav_basic without cas integration and with default bindings but untested. Posted to main directory.
